spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/admin
    username: admin
    password: admin
  jpa:
    hibernate:
      ddl-auto: create
logging:
  level:
    org.hibernate.engine.jdbc.env.internal.LobCreatorBuilderImpl: ERROR